# Generated by Django 2.2.1 on 2019-05-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoleCreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledistribution',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoleCreation.Roles'),
        ),
        migrations.AlterField(
            model_name='roledistribution',
            name='Task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.Tasks'),
        ),
    ]
