# Generated by Django 2.2.1 on 2019-05-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RoleCreation', '0002_auto_20190522_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('DisplayName', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('ProfilePic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Mobile', models.IntegerField(max_length=11)),
                ('password', models.CharField(max_length=30)),
                ('role', models.ManyToManyField(to='RoleCreation.Roles')),
            ],
        ),
    ]
